### ISSUE TITLE
Slack challenge

### ISSUE THREAD

**Issue by RicoMolina** [slackapi/template-announcement-approvals#3]
Hi, Im following instruction on the readme to enable this template.
The problem I have is when configuren "Event Subscription"
When I enter the "Request URL" provided by ngrok, slacks sends a challenge that is not responded, and it does not allow me to save settings. 
Any idea how to fix this?  
Thanks in advance.

**Comment by aoberoi** [comment]
You need to have the project running locally before you set up the event subscription. Please check that you've done this, and let us know if its still an issue. You should find more information about the incoming request and the response if you open up the [web console of ngrok](https://ngrok.com/docs#inspect).

**Comment by RicoMolina** [comment]
Hi!  I set it up locally.  Ngrok console displays classic 404 every time I try the challenge.

**Comment by aoberoi** [comment]
So the project is running, are we sure its served on the same port that ngrok is forwarding requests onto?

**Comment by RicoMolina** [comment]
Yeah.  Its 3000.  Default.   Ill build on a proper server instead of using ngrok and see how it goes.

**Comment by aoberoi** [comment]
One more option you have is to set `DEBUG=@slack/events-api:*` environment variable  when you start the node process. This will tell the underlying library to write debug logs out to the console. If you don't see any requests hitting the server, I think you have a URL, port, or routing problem. If you do see some requests, the contents of the logs would be useful in narrowing down where the problem might be.

**Comment by RicoMolina** [comment]
Worked in a new installation.  So probably some networking / port / forwardind thingy.   Thank you!
