### ISSUE TITLE
PostMessage Error: restricted_action

### ISSUE THREAD

**Issue by mithuns** [slackapi/template-announcement-approvals#6]
I am trying this code in glitch. And have made absolutely no code changes so far.

The only exception is , I made my ```#general``` channel restricted for ```Full Member```.
And now the bot wont post to the ```#general``` channel.
The output for authedchannels is this
```[ { value: 'ASDASDSD', label: '#general' } ]```
So, the bot does have atleast one channel general , where the bot is authorized to send messages.
Correct me if I am wrong?

And the output from this line 
https://github.com/slackapi/template-announcement-approvals/blob/master/src/postMessage.js#L124
is
```
PostMessage Error: restricted_action

PostMessage Error: channel_not_found
```

I feel it has something to do with the bot getting same permissions as the full members. Is there a way to give the bot elevated privileges somehow ?

**Comment by girliemac** [comment]
Bots are not considered a full member.
In this case, you may want to use "user token" (`xoxp-` token), instead of bot token, to post messages as a workaround and setting `as_user: false` to make it still appear to be from the bot user.

This is a little tricky thing about the token types...

**Comment by mithuns** [comment]
I will give it a try. Thanks for the response.

**Comment by mithuns** [comment]
Tried just testing it via [chat.postMessage/test](https://api.slack.com/methods/chat.postMessage/test) but now I get this as error response.
```
{
    "ok": false,
    "error": "missing_scope",
    "needed": "chat:write:user",
    "provided": "identify,bot"
}
```

**Comment by girliemac** [comment]
Aw sorry, I forgot to mention about permission scopes- user tokens have more granular scope setting (while bot token is more permissive), so you need to go to the config (OAuth and Permission setting) and enable the `chat:write:user` scope.

**Comment by girliemac** [comment]
Oh, also, in future we will make the bot tokens permission scopes more granular like the user token! The current model is a bit too permissive!

**Comment by mithuns** [comment]
Hey, got this working , so basically except for the last postAnnouncement, i just had to use bot token and set `as_user:true` and with postAnnouncement use user token and `as_user:false` and it worked just fine. Would it be ok if I send a pull request ? 
May be we can add to readme, about the missing scope `chat:write:user` as well.

**Comment by willswire** [comment]
@mithuns could you share the changes you made? Also encountering this issue.

**Comment by mithuns** [comment]
I had to use user token to post to chat.postmessage, with
`as_user:false`
and had to add a missing_scope that is
`chat:write:user`

**Comment by raghum01** [comment]
I couldn't find **chat:write:user** or  **chat:write:bot** scope.

Any idea, how to resolve this as I am getting following error.

{
    "ok": false,
    "error": "missing_scope",
    "needed": "chat:write:bot",
    "provided": "identify,channels:history,groups:history,channels:read"
}

**Comment by mithuns** [comment]
Seems like a lot of code has changed and api has also changed. 
Look at the activity here  https://github.com/slackapi/template-announcement-approvals/issues/13

**Comment by nrvmodi** [comment]
@raghum01 I have faced the same issue and I had given the solution by using https://stackoverflow.com/a/63446845/1294870
